data:
  train: 'data/imagenette/train'
  val: 'data/imagenette/val'
  batch_size: 128 # for test, batch_size//8 will be used.
  num_workers: 16
---
train:
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  decay:
    step: 150000
    gamma: 0.1
  summary_interval: 1
  checkpoint_interval: 250
  evaluation_interval: 250
---
model:
  channel: 78 # 'small regime'
  classes: 10
  graph0: 'ws-4-075-3.txt' # example: 'ws-4-075-3.txt'
  graph1: 'ws-4-075-3.txt'
  graph2: 'ws-4-075-3.txt'
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
